# Function takes a truth table generated by truthtable.m and reduces it
# to the simplest possible booleon function using the Quine-McCluskey
# method.
#
# EXAMPLE:
# >> qmprime(truthtable)
# ans =
#
# 00-=1;0P
# -10=1;1P
# 1-1=1;2P
#
# >>

function output = qmprime(input)

 # Reduces the input truth table down to only include true values.
 truecol = size(input,2);
 tablerows = size(input,1);
 tablecols = truecol;
 truetablerows = 0;
 variables = truecol-2;
 for truthtest = 1:tablerows,
   if (input(truthtest,truecol)=="1")
     truetablerows = truetablerows + 1;
     truetable(truetablerows,:)=input(truthtest,:);
   endif
 endfor

 # Repeatedly executes the qmsimplify function on the table until the output
 # is the same as the input, indicating that it cannot be further simplified.
 while (not(exist('output')))
   qmtable = qmsimplify(truetable);
   if (isequal(truetable,qmtable))
     output = qmtable;
   endif
   clear('truetable');
   truetable = qmtable;
 endwhile

