# Takes a truth table, of the format generated by truthtable.m or boole2table.m,
# where all false values have been removed, and simplifies it into fewer
# statements. If ran repeatedly, as done by table2boole.m, it will reduce it to
# the fewest possible number of prime implicants.

function output = qmsimplify(truetable)

# Establishes measurements of table, including how many rows and columns it has,
# and how many input variables are in the table.
truetablerows = size(truetable,1);
truetablecols = size(truetable,2);

for colcheck = 1:truetablecols,
  if (truetable(1,colcheck) == "=")
    variables = colcheck - 1;
  endif
endfor

# By default, marks all rows as being prime indicants.
for rowcheck = 1:truetablerows,
  truetable(rowcheck,variables+5) = "P";
endfor

# Sets the initial number of rows in the qmtable.
qmrows = 1;

for rowcheck = 1:truetablerows,
  for rowcompare = 1:truetablerows,
    if (truetable(rowcompare,variables+5) != "X" && truetable(rowcheck,variables+5) != "X")
      differences = 0;
      for colcheck = 1:variables,
        if (truetable(rowcheck,colcheck)!=truetable(rowcompare,colcheck))
          differences = differences + 1;
        endif
      endfor
      if (differences == 1)
        truetable(rowcheck,variables+5) = "X";    # If there is a single bit of difference between
        truetable(rowcompare,variables+5) = "X";  # This row and another, it marks it as not being
                                                  # a prime indicant.
        for colcheck = 1:variables,
          if (truetable(rowcheck,colcheck)!=truetable(rowcompare,colcheck))
            truetable(rowcheck,colcheck) = "-";
            truetable(rowcompare,colcheck) = "-";
            qmtable(qmrows,:) = truetable(rowcheck,:);
            qmrows = qmrows+1;
          endif
        endfor
      endif
    endif
  endfor
endfor

if (exist('qmtable'))
  # Deletes duuplicate rows from qmtable
  qmrows = size(qmtable,1);
  for rowcheck = 1:qmrows,
    for rowcompare = 1:qmrows,
      if (qmtable(rowcheck,:) == qmtable(rowcompare,:) && rowcheck != rowcompare)
        qmtable(rowcompare,:) = [];
      endif
    endfor
  endfor

  truetablerows = size(truetable,1);
  truetablecols = variables + 5;
  qmrows = size(qmtable,1);

  for rowcheck = 1:truetablerows,
    if (truetable(rowcheck,truetablecols)=="P")
      qmrows = qmrows + 1;
      qmtable(qmrows,:) = truetable(rowcheck,:);
    endif
  endfor

  output = qmtable;
else
  output = truetable;
endif
